name: LINUX CI
on:
  push:
    paths-ignore: []
    branches:
      - master
  pull_request:
    paths-ignore: []
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget gcc cmake liblz4-dev
          wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz -O go.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz

      - name: build
        run: PATH=$PATH:/usr/local/go/bin make build

      - name: run
        run: PATH=$PATH:/usr/local/go/bin make run
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        # only run this if manually invoked or a previous job failed
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.debug_enabled) || failure() }}
        with:
          detached: true
          timeout-minutes: 15
          
